version: "3.7"
services:
  rotundaspreita-web:
    image: iDarkQ/rotundaspreita-web:latest
    restart: always
    networks:
      - prisma-network
    expose:
      - 3003
    depends_on:
      db:
        condition: service_healthy
    # ports:
    #   - "3003:3003"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://0.0.0.0:3003 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  db:
    image: postgres:15
    restart: always
    expose:
      - 5433
    # ports:
    #   - "5433:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5433"]
      interval: 5s
      timeout: 2s
      retries: 20
    command: postgres -c listen_addresses='*' -p 5433
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    
networks:
  prisma-network:

volumes:
  postgres_data: